### ISSUE TITLE
how to change keybord layout

### ISSUE THREAD

**Issue by Sadra-jl** [cutefishos-ubuntu/cutefishos-ubuntu#13]
well, as English is my second language, I like to add a second keyboard layout and change them with "ALT + SHIFT" the problem is I can't find where to change them in settings. doing so is easy in Plasma but here,  I got a little confused.

**Comment by adielseffrin** [comment]
@Sadra-jl 
I'll let here how I set two layouts, Portuguese (be with abnt2 layout) and English (us with 105 keys layout).
Go to `/etc/X11/xorg.conf.d/` and create (or edit) the file `20-keyboard.conf`
Then use the options, configuring adqueate to your layouts

```
Section "InputClass"
        Identifier "keyboard"
        MatchIsKeyboard "yes"
        Option "XkbLayout" "br,us"
        Option "XkbModel" "abnt2,pc105"
        Option "XkbVariant" ""
        Option "XkbOptions" "grp:alt_shift_toggle"
EndSection
```

**Comment by Sadra-jl** [comment]
@adielseffrin thanks for your help, I'll mark the issue as complete.
